# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Niloy Saha
description: >- # this means to ignore newlines until "baseurl:"
  Masters student in computer science at IIT Kharagpur.

baseurl: "" # the subpath of your site, e.g. /blog
url: https://niloysh.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-avatar
  - jekyll-remote-theme


# theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack@gem-7.5.1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# change sidebar image
accent_image:
  background: '#202020' # provide a valid CSS background value
  overlay:    false     # set to true if you want a dark overlay

# add author
author:
  name:  Niloy Saha
  email: niloysaha.ns@gmail.com
  about: |
    Hi! I'm Niloy Saha.
  social:
    twitter: niloysh13
    github:  niloysh
    facebook: niloysh13
    linkedin: niloysh

defaults:
  - scope:
      path: research/index.md
    values:
      menu: true
      order: 1
  - scope:
      path: blog/index.md
    values:
      menu: true
      order: 2
  # - scope:
  #     path: research.md
  #     values:
  #     menu: true
  #     order: 2



