baseURL: 'https://niloysh.github.io/'
languageCode: 'en-us'
title: 'Niloy Saha'
theme: "niloysh"

menu:
  nav:
    - name: "Home"
      url: /
      weight: 1
    - name: "Publications"
      url: /publications/
      weight: 2
    - name: "Education & Experience"
      url: /education/
      weight: 3
    - name: "Awards & Achievements"
      url: /awards/
      weight: 4
    - name: "Presentations & Talks"
      url: /presentations/
      weight: 5
  
  social:
    - identifier: Email
      pre: <i class="fa-solid fa-envelope-open"></i>
      url: /contact
      weight: 1
    - identifier: Github
      pre: <i class="fa-brands fa-github"></i>
      url: https://github.com/niloysh/
      weight: 2
    - identifier: Linkedin
      pre: <i class="fa-brands fa-linkedin"></i>
      url: https://www.linkedin.com/in/niloysh/
      weight: 3
    - identifier: Scholar
      pre: <i class="ai ai-google-scholar-square"></i>
      url: https://scholar.google.ca/citations?user=gSAv2FUAAAAJ&hl=en
      weight: 4

# enable HTML markup in .md pages
markup:
  goldmark:
    renderer:
      unsafe: true

# add last modified date to pages
enableGitInfo: true
frontmatter:
  lastmod:
    - lastmod
    - :git
    - date
    - publishDate

# Google Analytics 4
ga_analytics: "G-M0M6NQTT2V"
