baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Niloy Saha'
theme = "niloysh"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Publications"
    url = "/publications/"
    weight = 2
  [[menu.nav]]
    name = "Education & Experience"
    url = "/education/"
    weight = 3
