baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Niloy Saha'
theme: "niloysh"

menu:
  nav:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Publications"
      url: "/publications/"
      weight: 2
    - name: "Education & Experience"
      url: "/education/"
      weight: 3
  
  social:
    - identifier: Email
      pre: <i class="fa-solid fa-envelope-open"></i>
      icon: fa-solid fa-envelope-open
      url: /contact
      weight: 1

